<?php
declare(strict_types=1);

namespace Qwizi\DVZSB\Commands;

use Qwizi\DVZSB\Bot;

abstract class Base
{
    public $bot;
    public $error;
    public $message;

    public function __construct(Bot $bot)
    {
        $this->bot = $bot;
    }

    public function getBot()
    {
        return $this->bot;
    }

    public function shout()
    {
        if (!$this->error) {
            $this->bot->shout($this->message);
        } else {
            $this->bot->shout($this->error);
        }
    }

    public function rebuildSettings()
    {
        $db = $this->bot->getDB();
        $mybb = $this->bot->getMybb();
        $query = $db->simple_select("settings", "value, name", "", array(
            'order_by' => 'title',
            'order_dir' => 'ASC',
        ));
        $settings = '';
        while ($setting = $db->fetch_array($query)) {
            $mybb->settings[$setting['name']] = $setting['value'];
            $setting['value'] = addcslashes($setting['value'], '\\"$');
            $settings .= "\$settings['{$setting['name']}'] = \"{$setting['value']}\";\n";
        }
        $settings = "<" . "?php\n/*********************************\ \n  DO NOT EDIT THIS FILE, PLEASE USE\n  THE SETTINGS EDITOR\n\*********************************/\n\n$settings\n";
        file_put_contents(MYBB_ROOT . 'inc/settings.php', $settings, LOCK_EX);
        $GLOBALS['settings'] = &$mybb->settings;
    }

    abstract protected function doAction(array $data): void;
}